import MarkdownIt from 'markdown-it'
import footnote from 'markdown-it-footnote'
import texmath from 'markdown-it-texmath'
import katex from 'katex'
import DOMPurify from 'dompurify'
import { highlightCode, knownLanguage, escapeHtml } from './highlight'
import { SlugTracker } from './slug'
import { taskLists, type TaskEnv, type TaskItem } from './tasklist'

export interface TocItem {
  id: string
  text: string
  level: number
}

export interface RenderedMarkdown {
  html: string
  toc: TocItem[]
  /** Task-list checkboxes, in document order, with their source lines. */
  tasks: TaskItem[]
}

const md: MarkdownIt = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: false,
  highlight: (code, lang) => highlightCode(code, lang || null)
})

md.use(taskLists)
md.use(footnote)
// Math via KaTeX: $inline$ and $$block$$. Rendered to HTML+MathML at parse time.
md.use(texmath, {
  engine: katex,
  delimiters: 'dollars',
  katexOptions: { throwOnError: false, strict: false }
})

// Headings carry a fold toggle so sections can be collapsed while reading.
md.renderer.rules.heading_open = (tokens, idx, options, _env, self) => {
  tokens[idx].attrJoin('class', 'md-heading')
  return (
    self.renderToken(tokens, idx, options) +
    `<button type="button" class="heading-fold" tabindex="-1"` +
    ` aria-expanded="true" title="Collapse section"></button>`
  )
}

// Wrap fenced code blocks in a container with a language label and copy button.
// `mermaid` blocks are emitted as a placeholder the Viewer renders into a diagram.
md.renderer.rules.fence = (tokens, idx) => {
  const token = tokens[idx]
  const lang = (token.info || '').trim().split(/\s+/)[0] || ''
  if (lang === 'mermaid') {
    // Keep the raw source in a hidden <pre> so it survives sanitization; the
    // Viewer reads its textContent and replaces the block with an SVG.
    return (
      `<div class="mermaid-block" data-processed="false">` +
      `<pre class="mermaid-source">${escapeHtml(token.content)}</pre>` +
      `<div class="mermaid-render"></div>` +
      `</div>`
    )
  }
  const highlighted = highlightCode(token.content, lang || null)
  const label = lang ? escapeHtml(lang) : 'text'
  const langClass = lang && knownLanguage(lang) ? ` language-${escapeHtml(lang)}` : ''
  return (
    `<div class="code-block">` +
    `<div class="code-block-header"><span class="code-lang">${label}</span>` +
    `<button type="button" class="code-copy" title="Copy code">Copy</button></div>` +
    `<pre class="code-pre"><code class="hljs${langClass}">${highlighted}</code></pre>` +
    `</div>`
  )
}

/**
 * Parse markdown, assign unique ids to headings and collect the table of
 * contents in the same pass so TOC ids always match the rendered document.
 */
export function renderMarkdown(source: string): RenderedMarkdown {
  const env: TaskEnv = {}
  const tokens = md.parse(source, env)
  const toc: TocItem[] = []
  const slugs = new SlugTracker()

  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i]
    if (token.type !== 'heading_open') continue
    const inline = tokens[i + 1]
    const text = inline && inline.type === 'inline' ? extractText(inline) : ''
    const id = slugs.unique(text)
    token.attrSet('id', id)
    toc.push({ id, text, level: Number(token.tag.slice(1)) })
  }

  const raw = md.renderer.render(tokens, md.options, env)
  return { html: sanitize(raw), toc, tasks: env.tasks ?? [] }
}

function extractText(inlineToken: { children?: { type: string; content: string }[] | null }): string {
  if (!inlineToken.children) return ''
  return inlineToken.children
    .filter((t) => t.type === 'text' || t.type === 'code_inline')
    .map((t) => t.content)
    .join('')
    .trim()
}

export function sanitize(html: string): string {
  return DOMPurify.sanitize(html, {
    // Allow MathML (KaTeX) alongside HTML and SVG.
    USE_PROFILES: { html: true, svg: true, mathMl: true },
    FORBID_TAGS: ['script', 'iframe', 'object', 'embed', 'form', 'base', 'meta', 'link'],
    // `style` is intentionally allowed: KaTeX positions glyphs with inline
    // styles. Inline CSS cannot execute script in modern engines, and we still
    // block scripts, iframes and event handlers below.
    FORBID_ATTR: ['onerror', 'onload', 'onclick'],
    ADD_ATTR: ['target'],
    // Heading ids are generated by us via slugify (trusted), and must survive
    // verbatim so TOC/anchor links match. DOM-clobbering protection otherwise
    // strips ids that collide with document properties (e.g. id="title").
    SANITIZE_DOM: false
  })
}
